"""Fix table structure

Revision ID: e75666eeef55
Revises: dd800033d35f
Create Date: 2025-03-04 22:44:14.913143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75666eeef55'
down_revision = 'dd800033d35f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
